apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productservice?useSSL=false
  DB_USER: root
  DB_PASS: "12042003"
  EUREKA_URI: http://discovery-service:8761/eureka
  ZIPKIN_URL: http://zipkin:9411
