apiVersion: v2
name: infrastructure
description: Umbrella chart for E-commerce Microservices Infrastructure (Redis, Kafka, Mongo, OpenSearch)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: kafka
    version: 26.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled

  - name: mongodb
    version: 14.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: opensearch
    version: 2.x.x
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
