apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shippingservice?useSSL=false
  DB_USER: root
  DB_PASS: "12042003"
  EUREKA_URI: http://discovery-service:8761/eureka
  USER_SERVICE_BASE_URL: http://user-service:8088
